In [5]:
import pandas as pd 
import numpy as np 
import time

In [9]:
w = np.random.rand(10000)
x = np.random.rand(10000)
tic = time.time()
z = np.dot(w,x)
toc = time.time()
print(f"vectorized took {(toc-tic)*1000} ms")
print(z)

vectorized took 0.3809928894042969 ms
2505.1629577634767


In [10]:
y = np.array([1,2,3])
d = np.array([6,7,8])
p = np.dot(y,d)
print(p)

44


In [12]:
v = np.random.rand(1000)
u = np.exp(v)

In [15]:
print(u[:3])

[1.34142678 1.52025037 1.50908065]


In [16]:
# broadcasting 
A = np.array([[56, 0, 4.4, 68.0], 
[1.2, 104, 52.0, 8.0], 
[1.8, 135, 99, .9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [18]:
# axis = 0, apply veritcally 
# axis = 1, apply horizonallt 
cal = A.sum(axis=0)
print(f"The number per column is {cal}")

The number per column is [ 59.  239.  155.4  76.9]


In [19]:
# cal is already reshaped, this is redundant 
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [21]:
cal.reshape(1,4) == cal

array([[ True,  True,  True,  True]])

In [22]:
100 +cal 

array([159. , 339. , 255.4, 176.9])

In [24]:
# contructing vectors for better programming
a = np.random.randn(5,1)
print(a.shape)

(5, 1)


In [25]:
np.dot(a, a.T)

array([[ 0.11467795, -0.63943893,  0.33734655,  0.16415834, -0.17719008],
       [-0.63943893,  3.56548175, -1.88102872, -0.91533926,  0.98800367],
       [ 0.33734655, -1.88102872,  0.99236773,  0.48290232, -0.52123764],
       [ 0.16415834, -0.91533926,  0.48290232,  0.23498815, -0.25364274],
       [-0.17719008,  0.98800367, -0.52123764, -0.25364274,  0.27377822]])

In [28]:
# rank 1 arrays (a= np.random.rand(5))
# needs to be a column vector (a = np.random.rand(5,1)) or row vector (1,5)
assert(a.shape == (5,1))
