In [1]:
import pandas as pd 
import numpy as np 
import time

In [9]:
w = np.random.rand(10000)
x = np.random.rand(10000)
tic = time.time()
z = np.dot(w,x)
toc = time.time()
print(f"vectorized took {(toc-tic)*1000} ms")
print(z)

vectorized took 0.3809928894042969 ms
2505.1629577634767


In [10]:
y = np.array([1,2,3])
d = np.array([6,7,8])
p = np.dot(y,d)
print(p)

44


In [12]:
v = np.random.rand(1000)
u = np.exp(v)

In [15]:
print(u[:3])

[1.34142678 1.52025037 1.50908065]


In [16]:
# broadcasting 
A = np.array([[56, 0, 4.4, 68.0], 
[1.2, 104, 52.0, 8.0], 
[1.8, 135, 99, .9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [18]:
# axis = 0, apply veritcally 
# axis = 1, apply horizonallt 
cal = A.sum(axis=0)
print(f"The number per column is {cal}")

The number per column is [ 59.  239.  155.4  76.9]


In [19]:
# cal is already reshaped, this is redundant 
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [21]:
cal.reshape(1,4) == cal

array([[ True,  True,  True,  True]])

In [22]:
100 +cal 

array([159. , 339. , 255.4, 176.9])

In [24]:
# contructing vectors for better programming
a = np.random.randn(5,1)
print(a.shape)

(5, 1)


In [25]:
np.dot(a, a.T)

array([[ 0.11467795, -0.63943893,  0.33734655,  0.16415834, -0.17719008],
       [-0.63943893,  3.56548175, -1.88102872, -0.91533926,  0.98800367],
       [ 0.33734655, -1.88102872,  0.99236773,  0.48290232, -0.52123764],
       [ 0.16415834, -0.91533926,  0.48290232,  0.23498815, -0.25364274],
       [-0.17719008,  0.98800367, -0.52123764, -0.25364274,  0.27377822]])

In [28]:
# rank 1 arrays (a= np.random.rand(5))
# needs to be a column vector (a = np.random.rand(5,1)) or row vector (1,5)
assert(a.shape == (5,1))


In [38]:
# quiz
a = np.random.randn(12288,150)
b = np.random.randn(150,45)
c = np.dot(a,b)
print(c)
print(c.shape)

[[ -3.59540841  19.69864108  13.85241769 ...  13.07044627 -14.66641118
   -4.59020087]
 [  0.35950658   8.94798211  -8.49810586 ...  -3.57270786   7.57362224
  -17.84897963]
 [ 15.32522731  21.15872772  21.01987208 ...  12.90121252   3.15689421
    2.42045141]
 ...
 [-13.58316526  -5.86139329  15.62406666 ...  -4.29579613  -0.35910979
   -3.10977769]
 [ -9.72677654  35.83711843   3.91704557 ...  10.42754857  -2.21115967
   -0.81845881]
 [ 10.88172795   5.31451062  13.41189294 ...   1.63616522  12.09836859
    6.69557273]]
(12288, 45)


In [36]:
a.shape

(4, 3)

In [37]:
a

array([[-2.25304832,  0.47192553,  0.03824717],
       [-1.02528385, -0.70109991,  0.12574249],
       [-1.33357019, -0.14483974,  0.17534227],
       [ 0.63655947, -0.2778664 ,  0.4245943 ]])

In [48]:

x = np.random.rand(3,4)
y = np.random.rand(4,1)
for i in range(3): 
    for j in range(4): 
        w[i][j] = x[i][j] + y[j]

TypeError: 'numpy.float64' object does not support item assignment

In [45]:
c.shape

(12288, 45)

In [49]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b 

In [50]:
c

array([[-0.005613  , -0.04678177, -0.01949701],
       [-0.11649591,  0.94041493, -1.18833401],
       [ 1.19844776,  0.65735991,  0.28104841]])

In [52]:
c.shape

(3, 3)

In [56]:
b

array([[-0.043014  ],
       [-0.88648132],
       [ 0.80234387]])

In [3]:
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])